feat: add logging config file
JanMate/happy_bank_core pull request #39
Opened 2022-02-22 15:12 UTC by Oleksandr6676

it adds logging config file

Closes #10

2022-02-22 15:14 UTC, Oleksandr6676 commented
@JanMate I will add logic call and exception handlers in this PR as well, if you don't mind. It was easier to test logger on the same branch with implemented logic

2022-02-23 10:17 UTC, Oleksandr6676 commented
__name__ didn't work for me.  I defined 1 more logger in config file and used it in the transaction module instead of root, so we could keep track on errors and files

2022-02-23 12:20 UTC, JanMate requested changes
@Oleksandr6676, I took a look on that and my suggested changes can offer us to call `logger.info("...")` and in logs see the module name without much effort.

Check this out and let me know if it works properly for you and even in docker container.

2022-02-23 12:20 UTC, JanMate commented on logging.conf
> +format=%(asctime)s - %(name)s - %(levelname)s - %(message)s
Please, get rid of this conf file and replace it by happy_bank_core/config/log.py module that contains the following code:
```suggestion
import logging


def setup_logging():
    logging.basicConfig(
        level=logging.DEBUG,
        format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    )

```

That should be enough and unit tests still pass.

2022-02-23 12:20 UTC, JanMate commented on happy_bank_core/logic/transaction.py
> +logger = logging.getLogger("transaction")
```suggestion
logger = logging.getLogger(__name__)
```

2022-02-23 12:20 UTC, JanMate commented on happy_bank_core/logic/transaction.py
> +import logging.config
```suggestion
import logging
```

2022-02-23 12:20 UTC, JanMate commented on happy_bank_core/app.py
> +import logging.config
```suggestion
import logging
```

2022-02-23 12:20 UTC, JanMate commented on happy_bank_core/app.py
>  from flask import Flask
```suggestion
from flask import Flask

```

2022-02-23 12:20 UTC, JanMate commented on happy_bank_core/app.py
> +logging.config.fileConfig("../logging.conf")
```suggestion
```

2022-02-23 12:20 UTC, JanMate commented on happy_bank_core/app.py
> +
```suggestion
from happy_bank_core.config.log import setup_logging

```

2022-02-23 12:20 UTC, JanMate commented on happy_bank_core/app.py
> +logger = logging.getLogger()
```suggestion
setup_logging()
logger = logging.getLogger(__name__)
```

2022-02-25 11:11 UTC, JanMate approved these changes

2022-02-25 11:13 UTC, merged